### PR TITLE
Migrate the project to Autotools

### PR DESCRIPTION
**Pull request by jgeboski**
This standardizes the project's build and install process by adapting
the well-known Autotools system. This simply migrates the previous
build.sh script into Autotools form. This does not attempt to clean up
or restructure anything to become more friendly to Autotools.

In order to better the integration of Autotools, the directories and
files should become more "friendly." The way things are currently laid
out, it requires removing and copying all over the place. What should
probably be done is to store only what differs between similar items,
and just move or replace strings, for instance, the index.themes.

### CODE REVIEW

**Comment by jgeboski** [comment]
Please double check `common/Makefile.am` just to ensure I did everything correctly in relation to the old `build.sh`.

**Comment by horst3180** [comment]
Building the 3.14 and 3.16 versions works fine. The 3.10 and 3.12 versions need special rules, so the build fails when I set `GNOME_VERSION="3.12"` or  `GNOME_VERSION="3.10"`.

Is there a reason, why `GNOME_VERSION` is hardcoded or is it just for testing?

**Comment by jgeboski** [comment]
Why must it fail with 3.10 or 3.12, aren't those supported?  The 3.16 value is just the default if GNOME is not found.  I should probably add some better error handling for invalid versions.

**Comment by horst3180** [comment]
3.10 and 3.12 are supported, but they need different build instructions. For example, there's no gtk-contained.css for these versions that could be moved around.
There's probably a way to unify this process without modifying the makefile.

Sorry it's a bit late, of course the `GNOME_VERSION` is correct.

**Comment by jgeboski** [comment]
I rebased the main patch and added better GNOME version handling.  See `m4/vertex-gnome.m4`.

**Pull request merged**
